DEFAULT_COUNTRY_CHOICE = "Select country..."

COUNTRIES = [
  "France",
  "Italy",
  "Austria",
  "New Zealand",
  "Chile",
  "Australia",
  "South Africa",
  "Spain",
  "United States",
  "Portugal",
  "Hungary",
  "Brazil",
  "Argentina",
  "Romania",
  "Germany",
  "Greece",
  "Mexico",
  "Moldova",
  "Switzerland",
  "Slovenia",
  "Israel",
  "Georgia",
  "Lebanon",
  "Uruguay",
  "Turkey",
  "Croatia",
  "China",
  "Slovakia",
  "Bulgaria",
  "Canada",
  "Luxembourg",
  "United Kingdom",
  "Czech Republic"
]